version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
      time: "12:00"
      day: monday
  - package-ecosystem: github-actions
    directory: .github
    schedule:
      interval: monthly
      time: "12:00"
      day: wednesday
