name: Golang CI
on:
  push:
  pull_request:

concurrency:
  group: goflat-go-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sast-go:
    permissions:
      contents: read
      pull-requests: write
      checks: write
      security-events: write
    uses: notdodo/github-actions/.github/workflows/go-security-scan.yml@go-sec-v0

  sast:
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    uses: notdodo/github-actions/.github/workflows/sast.yml@sast-v0

  build-and-test:
    permissions:
      contents: write
      pull-requests: write
      checks: write
    uses: notdodo/github-actions/.github/workflows/go-ci.yml@go-ci-v0
