name: Golang checks
on:
  push:
    branches:
      - main
    paths:
      - "**.go"
  pull_request:
    branches:
      - main
    paths:
      - "**.go"

jobs:
  checks:
    env:
      GO111MODULE: on
    name: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Install dependencies
        run: go get .
      - name: Test with the Go CLI
        run: go test

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: "-no-fail -fmt sarif -out results.sarif ./..."

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
