name: Cleanup caches by a branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    uses: notdodo/github-actions/.github/workflows/clean-branch-cache.yml@cleanup-v0
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
